# Generated by Django 3.1.7 on 2021-04-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
