# Generated by Django 3.1.7 on 2021-05-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210328_2004'),
        ('users', '0008_delete_notification'),
    ]

    operations = [
    ]
