# Generated by Django 3.1.7 on 2021-03-20 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galleries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.SmallIntegerField(choices=[(0, 'Public'), (1, 'Private')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSavedGalleries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='galleries.galleries')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_galleries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryArtworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('art_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.artworks')),
                ('gallery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.galleries')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='galleries',
            name='artworks',
            field=models.ManyToManyField(related_name='in_galleries', through='galleries.GalleryArtworks', to='artworks.Artworks'),
        ),
        migrations.AddField(
            model_name='galleries',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_galleries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='galleries',
            name='users',
            field=models.ManyToManyField(related_name='galleries', through='galleries.UserSavedGalleries', to=settings.AUTH_USER_MODEL),
        ),
    ]
