# Generated by Django 3.1.7 on 2021-04-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryartwork',
            name='position',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usersavedgallery',
            name='position',
            field=models.IntegerField(),
        ),
    ]
