# Generated by Django 3.1.7 on 2021-04-09 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_auto_20210408_0121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryartwork',
            options={'ordering': ['position']},
        ),
    ]
