# Generated by Django 3.1.7 on 2021-04-14 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galleries', '0003_auto_20210410_0158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='usersavedgallery',
            options={'ordering': ['position']},
        ),
        migrations.RenameField(
            model_name='galleryartwork',
            old_name='art_id',
            new_name='art',
        ),
        migrations.RenameField(
            model_name='galleryartwork',
            old_name='gallery_id',
            new_name='gallery',
        ),
        migrations.RemoveField(
            model_name='usersavedgallery',
            name='gallery_id',
        ),
        migrations.RemoveField(
            model_name='usersavedgallery',
            name='user_id',
        ),
        migrations.AddField(
            model_name='gallery',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersavedgallery',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.gallery'),
        ),
        migrations.AddField(
            model_name='usersavedgallery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='users',
            field=models.ManyToManyField(related_name='followed_galleries', through='galleries.UserSavedGallery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='galleryartwork',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersavedgallery',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
