# Generated by Django 3.1.7 on 2021-04-14 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0005_auto_20210414_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='users',
            new_name='followers',
        ),
    ]
