# Generated by Django 3.1.7 on 2021-03-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_auto_20210323_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True, default='No description', null=True),
        ),
    ]
