# Generated by Django 3.1.7 on 2021-05-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='notification',
        ),
    ]
