# Generated by Django 3.1.7 on 2021-04-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='activity',
            field=models.SmallIntegerField(choices=[(5, 'Gallery Like'), (6, 'Gallery Follow'), (1, 'Art Like'), (2, 'Follow'), (7, 'Reply'), (3, 'Comment'), (4, 'Comment Like'), (8, 'Upload')]),
        ),
    ]
